/**
 * Auto-generated test file for src/mcps/knowledge-skills/api-design.server.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { StrRayApiDesignServer } from "./api-design.server";

describe("api-design.server", () => {
  describe("StrRayApiDesignServer", () => {
    it("should be defined", () => {
      expect(StrRayApiDesignServer).toBeDefined();
    });
  });
});
