/**
 * Auto-generated test file for src/mcps/knowledge-skills/project-analysis.server.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { StrRayProjectAnalysisServer } from "./project-analysis.server";

describe("project-analysis.server", () => {
  describe("StrRayProjectAnalysisServer", () => {
    it("should be defined", () => {
      expect(StrRayProjectAnalysisServer).toBeDefined();
    });
  });
});
