/**
 * Auto-generated test file for src/mcps/architect-tools.server.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { StrRayArchitectToolsServer } from "./architect-tools.server";

describe("architect-tools.server", () => {
  describe("StrRayArchitectToolsServer", () => {
    it("should be defined", () => {
      expect(StrRayArchitectToolsServer).toBeDefined();
    });
  });
});
