/**
 * Auto-generated test file for src/mcps/enforcer-tools.server.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { StrRayEnforcerToolsServer } from "./enforcer-tools.server";

describe("enforcer-tools.server", () => {
  describe("StrRayEnforcerToolsServer", () => {
    it("should be defined", () => {
      expect(StrRayEnforcerToolsServer).toBeDefined();
    });
  });
});
