/**
 * Auto-generated test file for src/mcps/mcp-client.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { MCPClient, MCPClientManager, mcpClientManager } from "./mcp-client";

describe("mcp-client", () => {
  describe("MCPClient", () => {
    it("should instantiate", () => {
      const instance = new MCPClient();
      expect(instance).toBeInstanceOf(MCPClient);
    });
  });

  describe("MCPClientManager", () => {
    it("should instantiate", () => {
      const instance = new MCPClientManager();
      expect(instance).toBeInstanceOf(MCPClientManager);
    });
  });

  describe("mcpClientManager", () => {
    it("should be defined", () => {
      expect(mcpClientManager).toBeDefined();
    });
  });
});
