/**
 * Docusaurus Sidebar Configuration
 * Auto-generated by migrate-to-docusaurus.mjs
 * Generated: 2026-04-01
 */

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'category',
          label: 'Guides',
          link: { type: 'generated-index', slug: '/guides' },
          items: [{ type: 'autogenerated', dirName: 'guides' }],
        },
        {
          type: 'category',
          label: 'Configuration',
          link: { type: 'generated-index', slug: '/guides/configuration' },
          items: [{ type: 'autogenerated', dirName: 'guides/configuration' }],
        },
        {
          type: 'category',
          label: 'Getting Started',
          link: { type: 'generated-index', slug: '/guides/getting-started' },
          items: [{ type: 'autogenerated', dirName: 'guides/getting-started' }],
        },
        {
          type: 'category',
          label: 'Installation',
          link: { type: 'generated-index', slug: '/guides/installation' },
          items: [{ type: 'autogenerated', dirName: 'guides/installation' }],
        },
        {
          type: 'category',
          label: 'Quickstart',
          link: { type: 'generated-index', slug: '/guides/quickstart' },
          items: [{ type: 'autogenerated', dirName: 'guides/quickstart' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Releases',
      link: { type: 'generated-index', slug: '/releases' },
      items: [{ type: 'autogenerated', dirName: 'releases' }],
    },
    {
      type: 'category',
      label: 'Reflections',
      items: [
        {
          type: 'category',
          label: 'Reflections',
          link: { type: 'generated-index', slug: '/reflections' },
          items: [{ type: 'autogenerated', dirName: 'reflections' }],
        },
        {
          type: 'category',
          label: 'Archive',
          link: { type: 'generated-index', slug: '/reflections/archive' },
          items: [{ type: 'autogenerated', dirName: 'reflections/archive' }],
        },
        {
          type: 'category',
          label: 'Deep',
          link: { type: 'generated-index', slug: '/reflections/deep' },
          items: [{ type: 'autogenerated', dirName: 'reflections/deep' }],
        },
        {
          type: 'category',
          label: 'Sessions',
          link: { type: 'generated-index', slug: '/reflections/sessions' },
          items: [{ type: 'autogenerated', dirName: 'reflections/sessions' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        {
          type: 'category',
          label: 'Architecture',
          link: { type: 'generated-index', slug: '/architecture' },
          items: [{ type: 'autogenerated', dirName: 'architecture' }],
        },
        {
          type: 'category',
          label: 'Advanced',
          link: { type: 'generated-index', slug: '/architecture/advanced' },
          items: [{ type: 'autogenerated', dirName: 'architecture/advanced' }],
        },
        {
          type: 'category',
          label: 'Pipelines',
          link: { type: 'generated-index', slug: '/architecture/pipelines' },
          items: [{ type: 'autogenerated', dirName: 'architecture/pipelines' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      items: [
        {
          type: 'category',
          label: 'Agents',
          link: { type: 'generated-index', slug: '/agents' },
          items: [{ type: 'autogenerated', dirName: 'agents' }],
        },
        {
          type: 'category',
          label: 'Analysis',
          link: { type: 'generated-index', slug: '/agents/analysis' },
          items: [{ type: 'autogenerated', dirName: 'agents/analysis' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Research',
      items: [
        {
          type: 'category',
          label: 'Research',
          link: { type: 'generated-index', slug: '/research' },
          items: [{ type: 'autogenerated', dirName: 'research' }],
        },
        {
          type: 'category',
          label: 'Agency Agents',
          link: { type: 'generated-index', slug: '/research/agency-agents' },
          items: [{ type: 'autogenerated', dirName: 'research/agency-agents' }],
        },
        {
          type: 'category',
          label: 'Antigravity',
          link: { type: 'generated-index', slug: '/research/antigravity' },
          items: [{ type: 'autogenerated', dirName: 'research/antigravity' }],
        },
        {
          type: 'category',
          label: 'Impeccable',
          link: { type: 'generated-index', slug: '/research/impeccable' },
          items: [{ type: 'autogenerated', dirName: 'research/impeccable' }],
        },
        {
          type: 'category',
          label: 'Lightpanda',
          link: { type: 'generated-index', slug: '/research/lightpanda' },
          items: [{ type: 'autogenerated', dirName: 'research/lightpanda' }],
        },
        {
          type: 'category',
          label: 'Mirofish',
          link: { type: 'generated-index', slug: '/research/mirofish' },
          items: [{ type: 'autogenerated', dirName: 'research/mirofish' }],
        },
        {
          type: 'category',
          label: 'Openclaw',
          link: { type: 'generated-index', slug: '/research/openclaw' },
          items: [{ type: 'autogenerated', dirName: 'research/openclaw' }],
        },
        {
          type: 'category',
          label: 'Openviking',
          link: { type: 'generated-index', slug: '/research/openviking' },
          items: [{ type: 'autogenerated', dirName: 'research/openviking' }],
        },
        {
          type: 'category',
          label: 'Superpowers',
          link: { type: 'generated-index', slug: '/research/superpowers' },
          items: [{ type: 'autogenerated', dirName: 'research/superpowers' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      link: { type: 'generated-index', slug: '/deployment' },
      items: [{ type: 'autogenerated', dirName: 'deployment' }],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        {
          type: 'category',
          label: 'Security',
          link: { type: 'generated-index', slug: '/security' },
          items: [{ type: 'autogenerated', dirName: 'security' }],
        },
        {
          type: 'category',
          label: 'Compliance.Md',
          link: { type: 'generated-index', slug: '/security/compliance.md' },
          items: [{ type: 'autogenerated', dirName: 'security/compliance.md' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      link: { type: 'generated-index', slug: '/testing' },
      items: [{ type: 'autogenerated', dirName: 'testing' }],
    },
    {
      type: 'category',
      label: 'Performance',
      link: { type: 'generated-index', slug: '/performance' },
      items: [{ type: 'autogenerated', dirName: 'performance' }],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Reference',
          link: { type: 'generated-index', slug: '/reference' },
          items: [{ type: 'autogenerated', dirName: 'reference' }],
        },
        {
          type: 'category',
          label: 'Commands',
          link: { type: 'generated-index', slug: '/reference/commands' },
          items: [{ type: 'autogenerated', dirName: 'reference/commands' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      link: { type: 'generated-index', slug: '/tools' },
      items: [{ type: 'autogenerated', dirName: 'tools' }],
    },
    {
      type: 'category',
      label: 'Migrations',
      link: { type: 'generated-index', slug: '/migrations' },
      items: [{ type: 'autogenerated', dirName: 'migrations' }],
    },
    {
      type: 'category',
      label: 'Integration',
      link: { type: 'generated-index', slug: '/integration' },
      items: [{ type: 'autogenerated', dirName: 'integration' }],
    },
    {
      type: 'category',
      label: 'API',
      link: { type: 'generated-index', slug: '/api' },
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    {
      type: 'category',
      label: 'Development',
      link: { type: 'generated-index', slug: '/development' },
      items: [{ type: 'autogenerated', dirName: 'development' }],
    },
    {
      type: 'category',
      label: 'Roadmap',
      link: { type: 'generated-index', slug: '/roadmap' },
      items: [{ type: 'autogenerated', dirName: 'roadmap' }],
    },
    {
      type: 'category',
      label: 'Governance',
      link: { type: 'generated-index', slug: '/governance' },
      items: [{ type: 'autogenerated', dirName: 'governance' }],
    },
    {
      type: 'category',
      label: 'Analytics',
      link: { type: 'generated-index', slug: '/analytics' },
      items: [{ type: 'autogenerated', dirName: 'analytics' }],
    },
    {
      type: 'category',
      label: 'Reports',
      link: { type: 'generated-index', slug: '/reports' },
      items: [{ type: 'autogenerated', dirName: 'reports' }],
    },
    {
      type: 'category',
      label: 'Enhancements',
      link: { type: 'generated-index', slug: '/enhancements' },
      items: [{ type: 'autogenerated', dirName: 'enhancements' }],
    },
    {
      type: 'category',
      label: 'Implementation Status',
      link: { type: 'generated-index', slug: '/implementation-status' },
      items: [{ type: 'autogenerated', dirName: 'implementation-status' }],
    },
    {
      type: 'category',
      label: 'Implementation Summary',
      link: { type: 'generated-index', slug: '/implementation-summary' },
      items: [{ type: 'autogenerated', dirName: 'implementation-summary' }],
    },
    {
      type: 'category',
      label: 'Selection',
      link: { type: 'generated-index', slug: '/selection' },
      items: [{ type: 'autogenerated', dirName: 'selection' }],
    },
    {
      type: 'category',
      label: 'Sessions',
      link: { type: 'generated-index', slug: '/sessions' },
      items: [{ type: 'autogenerated', dirName: 'sessions' }],
    },
    {
      type: 'category',
      label: 'Operations',
      link: { type: 'generated-index', slug: '/operations' },
      items: [{ type: 'autogenerated', dirName: 'operations' }],
    },
  ],
};

export default sidebars;
