import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    'introduction',
    {
      type: 'category',
      label: 'Wear',
      items: [
        'guides/getting-started',
        'guides/integrations',
        'architecture/GROK_GUIDE',
        'guides/autonomy-command',
        'guides/consumer-migration',
      ],
    },
    {
      type: 'category',
      label: '4.0',
      items: [
        'architecture/v4-vision',
        'architecture/ecosystem',
        'architecture/v4-now',
        'architecture/v4-foundry',
        'architecture/v4-left',
        'guides/v3-temperament',
        'architecture/v3-from-v2',
        'architecture/v3-museum',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/features-since-3.1',
        'guides/features-json',
        'guides/memory-routing',
        'guides/repertoire',
        'guides/station-vs-repertoire',
        'guides/host-truth',
        'guides/memory-wake',
        'guides/aside-context',
        'guides/user-asides',
        'guides/parallel-work-tracks',
        'guides/self-hosting-dynamo',
        'guides/house',
      ],
    },
    {
      type: 'category',
      label: 'Plates',
      link: { type: 'doc', id: 'plates/index' },
      items: [
        'plates/routing',
        'plates/governance',
        'plates/boot',
        'plates/orchestration',
        'plates/processor',
        'plates/reporting',
        'plates/memory-recall',
        'plates/stamp-plate',
        'plates/house',
        'plates/live-mesh',
        'plates/review',
        'plates/goggles',
        'plates/suit',
        'plates/kits',
        'plates/host-pack',
        'plates/glossary',
        'plates/record-map',
        'plates/write-home',
        'plates/activity-log',
        'plates/session-capture',
        'plates/suit-wear',
        'plates/suit-organs',
        'plates/station-card',
        'plates/notes-page',
        'plates/reflection-page',
        'plates/site-manual',
        'plates/package-face',
        'plates/suit-settings',
        'plates/trail-state',
        'plates/inference-files',
        'plates/grok-compact',
        'plates/payload-heat',
        'plates/station-heat',
        'plates/pickup-stamp',
        'plates/cursor-compact',
        'plates/work-fresh',
        'plates/kept-line',
        'plates/lens-gate',
        'plates/pre-tool',
        'plates/lens-page',
        'plates/grokbot',
      ],
    },
    'full-reference',
    'agents/README',
    'mcp/README',
  ],
};

export default sidebars;
