/**
 * Docusaurus Sidebar Configuration
 * Working config for docs/
 */

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'xray — Three-Subsystem',
      collapsed: false,
      items: [
        'README',
        {
          type: 'category',
          label: 'Core Architecture',
          items: [
            {
              type: 'autogenerated',
              dirName: 'architecture',
            },
          ],
        },
        {
          type: 'category',
          label: 'MCP Orchestrator & thinDispatch',
          items: [
            {
              type: 'autogenerated',
              dirName: 'mcp',
            },
          ],
        },
        {
          type: 'category',
          label: 'Agents (YML SSOT)',
          items: [
            {
              type: 'autogenerated',
              dirName: 'agents',
            },
          ],
        },
        {
          type: 'category',
          label: 'Governance & Dynamo',
          items: [
            {
              type: 'autogenerated',
              dirName: 'governance',
            },
          ],
        },
        {
          type: 'category',
          label: 'Security & Codex',
          items: [
            {
              type: 'autogenerated',
              dirName: 'security',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;