/**
 * Auto-generated test file for src/processors/agents-md-validation-processor.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import {
  AgentsMdValidationProcessor,
  agentsMdValidationProcessor,
} from "./agents-md-validation-processor";

describe("agents-md-validation-processor", () => {
  describe("AgentsMdValidationProcessor", () => {
    it("should instantiate", () => {
      const instance = new AgentsMdValidationProcessor();
      expect(instance).toBeInstanceOf(AgentsMdValidationProcessor);
    });
  });

  describe("agentsMdValidationProcessor", () => {
    it("should be defined", () => {
      expect(agentsMdValidationProcessor).toBeDefined();
    });
  });
});
