/**
 * Auto-generated test file for src/processors/processor-manager.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { ProcessorManager } from "./processor-manager";

describe("processor-manager", () => {
  describe("ProcessorManager", () => {
    it("should instantiate", () => {
      const instance = new ProcessorManager();
      expect(instance).toBeInstanceOf(ProcessorManager);
    });
  });
});
