/**
 * Auto-generated test file for src/processors/version-compliance-processor.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { VersionComplianceProcessor, versionComplianceProcessor } from "./version-compliance-processor";

describe("version-compliance-processor", () => {
  describe("VersionComplianceProcessor", () => {
    it("should instantiate", () => {
      const instance = new VersionComplianceProcessor();
      expect(instance).toBeInstanceOf(VersionComplianceProcessor);
    });
  });

  describe("versionComplianceProcessor", () => {
    it("should be defined", () => {
      expect(versionComplianceProcessor).toBeDefined();
    });
  });
});
