echo "Checking TypeScript syntax..."
npx tsc --noEmit --project . --skipLibCheck 2>&1 && echo "✅ TypeScript syntax valid" || echo "❌ TypeScript syntax error"
echo ""
echo "Checking build compilation..."
npm run typecheck > /dev/null && echo "✅ Build compilation successful" || echo "❌ Build compilation failed"