/**
 * Auto-generated test file for src/__tests__/utils/test-helpers.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import {
  MockFileSystem,
  MockCodexGenerator,
  MockContextFactory,
  TestDataFactory,
  PerformanceTestUtils,
  MemoryTestUtils,
  AsyncTestUtils,
} from "./test-helpers";

describe("test-helpers", () => {
  describe("MockFileSystem", () => {
    it("should instantiate", () => {
      const instance = new MockFileSystem();
      expect(instance).toBeInstanceOf(MockFileSystem);
    });
  });

  describe("MockCodexGenerator", () => {
    it("should instantiate", () => {
      const instance = new MockCodexGenerator();
      expect(instance).toBeInstanceOf(MockCodexGenerator);
    });
  });

  describe("MockContextFactory", () => {
    it("should instantiate", () => {
      const instance = new MockContextFactory();
      expect(instance).toBeInstanceOf(MockContextFactory);
    });
  });

  describe("TestDataFactory", () => {
    it("should instantiate", () => {
      const instance = new TestDataFactory();
      expect(instance).toBeInstanceOf(TestDataFactory);
    });
  });

  describe("PerformanceTestUtils", () => {
    it("should instantiate", () => {
      const instance = new PerformanceTestUtils();
      expect(instance).toBeInstanceOf(PerformanceTestUtils);
    });
  });

  describe("MemoryTestUtils", () => {
    it("should instantiate", () => {
      const instance = new MemoryTestUtils();
      expect(instance).toBeInstanceOf(MemoryTestUtils);
    });
  });

  describe("AsyncTestUtils", () => {
    it("should instantiate", () => {
      const instance = new AsyncTestUtils();
      expect(instance).toBeInstanceOf(AsyncTestUtils);
    });
  });
});
