/**
 * Auto-generated test file for src/utils/language-detector.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { detectProjectLanguage, getTestFilePath, buildTestCommand, LANGUAGE_CONFIGS, languageDetector } from "./language-detector";

describe("language-detector", () => {
  describe("detectProjectLanguage", () => {
    it("should be defined", () => {
      expect(typeof detectProjectLanguage).toBe("function");
    });

    it("should handle basic case", async () => {
      // Test with current directory
      const result = await detectProjectLanguage(process.cwd());
      expect(result).toBeDefined();
    });
  });

  describe("getTestFilePath", () => {
    it("should be defined", () => {
      expect(typeof getTestFilePath).toBe("function");
    });

    it("should handle basic case", async () => {
      // Test with a sample project language
      const result = getTestFilePath("src/utils/helper.ts", {
        language: "TypeScript",
        testFramework: "Vitest",
        testCommand: "vitest run",
        testFilePattern: "*.test.ts",
        configFiles: ["vitest.config.ts"]
      });
      expect(result).toBeDefined();
    });
  });

  describe("buildTestCommand", () => {
    it("should be defined", () => {
      expect(typeof buildTestCommand).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = buildTestCommand({
        language: "TypeScript",
        testFramework: "Vitest",
        testCommand: "vitest run",
        testFilePattern: "*.test.ts",
        configFiles: []
      });
      expect(result).toBeDefined();
    });
  });

  describe("LANGUAGE_CONFIGS", () => {
    it("should be defined", () => {
      expect(LANGUAGE_CONFIGS).toBeDefined();
      expect(Array.isArray(LANGUAGE_CONFIGS)).toBe(true);
      expect(LANGUAGE_CONFIGS.length).toBeGreaterThan(0);
    });
  });

  describe("languageDetector", () => {
    it("should be defined", () => {
      expect(languageDetector).toBeDefined();
      expect(typeof languageDetector.detect).toBe("function");
      expect(typeof languageDetector.getTestFilePath).toBe("function");
      expect(typeof languageDetector.buildTestCommand).toBe("function");
    });
  });
});
