import { describe, it, expect, vi, beforeEach } from "vitest";
import {
  AGENT_REGISTRY,
  getActiveAgents,
  getAgentEntry,
  isAllowedAgent,
  getAgentCapabilities,
  validateRegistryConsistency,
} from "../../agents/registry.js";
import { DEFAULT_AGENTS } from "../../config/default-agents.js";
import { builtinAgents } from "../../agents/index.js";
import * as fs from "fs";
import * as path from "path";

describe("Agent Registry Integration", () => {
  it("registry has agents including deprecated ones", () => {
    const keys = Object.keys(AGENT_REGISTRY);
    expect(keys.length).toBeGreaterThan(20);
  });

  it("should have some active agents", () => {
    const active = Object.entries(AGENT_REGISTRY).filter(
      ([, e]) => e.status === "active"
    );
    expect(active.length).toBeGreaterThan(0);
  });

  it("getActiveAgents returns expected count", () => {
    const active = getActiveAgents();
    expect(active.length).toBeGreaterThan(0);
  });

  it("getAgentEntry returns correct data", () => {
    const entry = getAgentEntry("architect");
    expect(entry).toBeDefined();
    expect(entry!.name).toBe("architect");
    expect(entry!.mode).toBe("primary");
    expect(entry!.capabilities.length).toBeGreaterThan(0);
  });

  it("getAgentEntry returns undefined for unknown agent", () => {
    expect(getAgentEntry("nonexistent-agent")).toBeUndefined();
  });

  it("isAllowedAgent accepts registered active agents", () => {
    expect(isAllowedAgent("architect")).toBe(true);
    expect(isAllowedAgent("code-reviewer")).toBe(true);
  });

  it("isAllowedAgent rejects unknown agents", () => {
    expect(isAllowedAgent("phantom-agent")).toBe(false);
    expect(isAllowedAgent("")).toBe(false);
  });

  it("getAgentCapabilities returns capabilities for known agent", () => {
    const caps = getAgentCapabilities("architect");
    expect(caps.length).toBeGreaterThan(0);
    expect(caps).toContain("design");
  });

  it("getAgentCapabilities returns empty array for unknown agent", () => {
    expect(getAgentCapabilities("nonexistent")).toEqual([]);
  });

  it("validateRegistryConsistency runs", () => {
    const result = validateRegistryConsistency();
    expect(result).toBeDefined();
  });

  it("DEFAULT_AGENTS derives from registry", () => {
    const names = DEFAULT_AGENTS.map((a) => a.name);
    expect(names.length).toBeGreaterThan(0);
    expect(names).toContain("architect");
  });

  it("builtinAgents barrel has same keys as registry", () => {
    const barrelKeys = Object.keys(builtinAgents).sort();
    const registryKeys = Object.keys(AGENT_REGISTRY).sort();
    expect(barrelKeys).toEqual(registryKeys);
  });

  it("each agent has a .ts file in src/agents/", () => {
    const agentsDir = path.resolve(process.cwd(), "src/agents");
    for (const key of Object.keys(AGENT_REGISTRY)) {
      const filePath = path.join(agentsDir, `${key}.ts`);
      expect(fs.existsSync(filePath)).toBe(true);
    }
  });

  it("routing-mappings.json agents all exist in registry", () => {
    const srcPath = path.resolve(process.cwd(), "src/xray/routing-mappings.json");
    const genPath = path.resolve(process.cwd(), ".xray/routing-mappings.json");
    const mappingsPath = fs.existsSync(srcPath) ? srcPath : genPath;
    if (!fs.existsSync(mappingsPath)) return; // source not available on fresh clone
    const mappings = JSON.parse(fs.readFileSync(mappingsPath, "utf-8"));
    const registryKeys = new Set(Object.keys(AGENT_REGISTRY));

    for (const mapping of mappings) {
      expect(registryKeys.has(mapping.agent)).toBe(true);
    }
  });

  it("routing-mappings.json has no autoGenerated entries", () => {
    const srcPath = path.resolve(process.cwd(), "src/xray/routing-mappings.json");
    const genPath = path.resolve(process.cwd(), ".xray/routing-mappings.json");
    const mappingsPath = fs.existsSync(srcPath) ? srcPath : genPath;
    if (!fs.existsSync(mappingsPath)) return;
    const mappings = JSON.parse(fs.readFileSync(mappingsPath, "utf-8"));
    const autoGen = mappings.filter((m: any) => m.autoGenerated === true);
    expect(autoGen).toHaveLength(0);
  });

  it("each registry entry has valid mode and status", () => {
    for (const [key, entry] of Object.entries(AGENT_REGISTRY)) {
      expect(["primary", "subagent"]).toContain(entry.mode);
      expect(["active", "inactive"]).toContain(entry.status);
      expect(entry.name).toBe(key);
      expect(entry.capabilities.length).toBeGreaterThan(0);
      // Skip deprecated agents which have 0 capacity/tasks
      if (entry.status === "active") {
        expect(entry.capacity).toBeGreaterThan(0);
        expect(entry.concurrentTasks).toBeGreaterThanOrEqual(1);
      }
    }
  });

  it("should have primary agents configured", () => {
    const primaries = Object.entries(AGENT_REGISTRY)
      .filter(([, e]) => e.mode === "primary")
      .map(([k]) => k);
    expect(primaries).toContain("architect");
    expect(primaries.length).toBeGreaterThan(0);
  });

  it("delegator getAvailableAgents uses DEFAULT_AGENTS from registry", async () => {
    const { AgentDelegator } = await import("../../delegation/agent-delegator.js");
    const mockStateManager = {
      get: vi.fn().mockReturnValue(undefined),
    };
    const mockConfigLoader = {
      getConfig: vi.fn().mockReturnValue({}),
    };
    const delegator = new AgentDelegator(mockStateManager, mockConfigLoader);
    const agents = delegator.getAvailableAgents();
    expect(agents).toHaveLength(22);
    expect(agents[0].name).toBeDefined();
    expect(agents[0].capabilities).toBeDefined();
  });
});
