import { describe, it, expect, vi, beforeEach } from "vitest";
import {
  AGENT_REGISTRY,
  getActiveAgents,
  getAgentEntry,
  isAllowedAgent,
  getAgentCapabilities,
  validateRegistryConsistency,
} from "../../agents/registry.js";
import { DEFAULT_AGENTS } from "../../config/default-agents.js";
import { builtinAgents } from "../../agents/index.js";
import * as fs from "fs";
import * as path from "path";

describe("Agent Registry Integration", () => {
  it("registry has exactly 23 agents", () => {
    const keys = Object.keys(AGENT_REGISTRY);
    expect(keys).toHaveLength(23);
  });

  it("all registry agents are active", () => {
    const inactive = Object.entries(AGENT_REGISTRY).filter(
      ([, e]) => e.status !== "active"
    );
    expect(inactive).toHaveLength(0);
  });

  it("getActiveAgents returns all 23 names", () => {
    const active = getActiveAgents();
    expect(active).toHaveLength(23);
    expect(active).toContain("enforcer");
    expect(active).toContain("orchestrator");
    expect(active).toContain("tech-writer");
  });

  it("getAgentEntry returns correct data", () => {
    const entry = getAgentEntry("enforcer");
    expect(entry).toBeDefined();
    expect(entry!.name).toBe("enforcer");
    expect(entry!.mode).toBe("primary");
    expect(entry!.capabilities.length).toBeGreaterThan(0);
  });

  it("getAgentEntry returns undefined for unknown agent", () => {
    expect(getAgentEntry("nonexistent-agent")).toBeUndefined();
  });

  it("isAllowedAgent accepts registered active agents", () => {
    expect(isAllowedAgent("enforcer")).toBe(true);
    expect(isAllowedAgent("code-reviewer")).toBe(true);
  });

  it("isAllowedAgent rejects unknown agents", () => {
    expect(isAllowedAgent("phantom-agent")).toBe(false);
    expect(isAllowedAgent("")).toBe(false);
  });

  it("getAgentCapabilities returns capabilities for known agent", () => {
    const caps = getAgentCapabilities("architect");
    expect(caps.length).toBeGreaterThan(0);
    expect(caps).toContain("design");
  });

  it("getAgentCapabilities returns empty array for unknown agent", () => {
    expect(getAgentCapabilities("nonexistent")).toEqual([]);
  });

  it("validateRegistryConsistency passes with no errors", () => {
    const result = validateRegistryConsistency();
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  it("DEFAULT_AGENTS derives all 23 entries from registry", () => {
    expect(DEFAULT_AGENTS).toHaveLength(23);
    const names = DEFAULT_AGENTS.map((a) => a.name).sort();
    const registryNames = Object.keys(AGENT_REGISTRY).sort();
    expect(names).toEqual(registryNames);
  });

  it("builtinAgents barrel has same keys as registry", () => {
    const barrelKeys = Object.keys(builtinAgents).sort();
    const registryKeys = Object.keys(AGENT_REGISTRY).sort();
    expect(barrelKeys).toEqual(registryKeys);
  });

  it("each agent has a .ts file in src/agents/", () => {
    const agentsDir = path.resolve(process.cwd(), "src/agents");
    for (const key of Object.keys(AGENT_REGISTRY)) {
      const filePath = path.join(agentsDir, `${key}.ts`);
      expect(fs.existsSync(filePath)).toBe(true);
    }
  });

  it("routing-mappings.json agents all exist in registry", () => {
    const mappingsPath = path.resolve(
      process.cwd(),
      ".opencode/strray/routing-mappings.json"
    );
    const mappings = JSON.parse(fs.readFileSync(mappingsPath, "utf-8"));
    const registryKeys = new Set(Object.keys(AGENT_REGISTRY));

    for (const mapping of mappings) {
      expect(registryKeys.has(mapping.agent)).toBe(true);
    }
  });

  it("routing-mappings.json has no autoGenerated entries", () => {
    const mappingsPath = path.resolve(
      process.cwd(),
      ".opencode/strray/routing-mappings.json"
    );
    const mappings = JSON.parse(fs.readFileSync(mappingsPath, "utf-8"));
    const autoGen = mappings.filter((m: any) => m.autoGenerated === true);
    expect(autoGen).toHaveLength(0);
  });

  it("each registry entry has valid mode and status", () => {
    for (const [key, entry] of Object.entries(AGENT_REGISTRY)) {
      expect(["primary", "subagent"]).toContain(entry.mode);
      expect(["active", "inactive"]).toContain(entry.status);
      expect(entry.name).toBe(key);
      expect(entry.capabilities.length).toBeGreaterThan(0);
      expect(entry.capacity).toBeGreaterThan(0);
      expect(entry.concurrentTasks).toBeGreaterThanOrEqual(1);
    }
  });

  it("primary agents: enforcer, architect, orchestrator", () => {
    const primaries = Object.entries(AGENT_REGISTRY)
      .filter(([, e]) => e.mode === "primary")
      .map(([k]) => k);
    expect(primaries).toEqual(expect.arrayContaining(["enforcer", "architect", "orchestrator"]));
    expect(primaries.length).toBe(3);
  });

  it("delegator getAvailableAgents uses DEFAULT_AGENTS from registry", async () => {
    const { AgentDelegator } = await import("../../delegation/agent-delegator.js");
    const mockStateManager = {
      get: vi.fn().mockReturnValue(undefined),
    };
    const mockConfigLoader = {
      getConfig: vi.fn().mockReturnValue({}),
    };
    const delegator = new AgentDelegator(mockStateManager, mockConfigLoader);
    const agents = delegator.getAvailableAgents();
    expect(agents).toHaveLength(23);
    expect(agents[0].name).toBeDefined();
    expect(agents[0].capabilities).toBeDefined();
  });
});
