/**
 * Auto-generated test file for src/postprocessor/PostProcessor.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { PostProcessor } from "./PostProcessor";
import { StringRayStateManager } from "../state/state-manager.js";

describe("PostProcessor", () => {
  describe("PostProcessor", () => {
    it("should instantiate", () => {
      const stateManager = new StringRayStateManager();
      const instance = new PostProcessor(stateManager);
      expect(instance).toBeInstanceOf(PostProcessor);
    });
  });
});
