/**
 * Auto-generated test file for src/postprocessor/PostProcessor.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { PostProcessor } from "./PostProcessor";

describe("PostProcessor", () => {
  describe("PostProcessor", () => {
    it("should instantiate", () => {
      const instance = new PostProcessor();
      expect(instance).toBeInstanceOf(PostProcessor);
    });
  });
});
