/**
 * Auto-generated test file for src/agents/explore.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { explore } from "./explore";

describe("explore", () => {
  describe("explore", () => {
    it("should be defined", () => {
      expect(explore).toBeDefined();
    });
  });
});
