import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '../../..');

describe('lead cadence encode — peer can find the beat', () => {
  const cadence = path.join(root, 'grok-bot', 'ops', 'LEAD-CADENCE.md');
  const catalog = path.join(root, 'grok-bot', 'ops', 'OPS-CATALOG.md');
  const orchestrator = path.join(root, 'src', 'skills', 'orchestrator', 'SKILL.md');
  const agents = path.join(root, 'AGENTS.md');

  it('ships the disk SSOT and catalogs it', () => {
    expect(existsSync(cadence)).toBe(true);
    const text = readFileSync(cadence, 'utf8');
    expect(text).toMatch(/Peer test/);
    expect(text).toMatch(/Live tick/);
    expect(text).toMatch(/A friend would hear:/);
    expect(text).toMatch(/Jargon is not the job/);
    expect(text).toMatch(/### Feat rebase/);
    expect(text).toMatch(/Engine cadence/);
    expect(text).toMatch(/Ship it local/);
    expect(text).toMatch(/### Planes/);
    expect(text).toMatch(/code, OP-PROC, model, suit, mill, host, and test\/ship/);
    expect(text).toMatch(/Test then ship is the hero/);
    expect(text).toMatch(/Ship without that proof is the catastrophe/);
    expect(text).toMatch(/refreshes a changed definition/);
    expect(text).toMatch(/stamper strips that patch ref from shipped guides and shipped OP-PROC/);
    expect(text).toMatch(/does not edit Station, NOTES, dest, or node_modules/);
    expect(text).toMatch(/It does not publish/);
    expect(text).toMatch(/not fully proved/);
    expect(text).toMatch(/Do not freeze the live cut/);
    expect(text).toMatch(/The lead keeps control/);
    expect(text).toMatch(/wears the applicable 0xRay suit/);
    expect(text).toMatch(/answer the original message again from this seat/);
    expect(text).toMatch(/Do not spend the loop reciting dest names, mill liturgy, or host mantras/);
    expect(text).toMatch(/Codex 69/);
    expect(text).toMatch(/Dummy exists to \*\*test `SKILLS\.md`\*\*/);
    expect(text).toMatch(/Same-sess bodies exist to \*\*keep context\*\*/);
    expect(text).toMatch(/npm publish --access public/);
    expect(text).toMatch(/Do \*\*not\*\* press Enter/);
    expect(text).toMatch(/every time run `npm publish --access public`/);
    expect(text).toMatch(/Do \*\*not\*\* ask the human to type a 6-digit authenticator code/);
    expect(text).toMatch(/do \*\*not\*\* `npm logout`/);
    expect(text).not.toMatch(/If the CLI returns `EOTP`.*`npm logout`/);
    expect(text).toMatch(/Do not move on until the new version is polled live/);
    expect(text).toMatch(/Registry install \(live verify\)/);
    expect(text).toMatch(/npm view` is not an install/);
    expect(text).toMatch(/REQUIRED_PACK_PATHS/);
    expect(text).toMatch(/Peer boot/);
    expect(text).toMatch(/bc-49e17122-b167-5204-a36f-e62a6e2aba00/);
    expect(text).toMatch(/Fresh \+ upgrade live-verify/);
    expect(text).toMatch(/leftover `\.opencode\/init\.sh`/);
    expect(text).toMatch(/Always a branch/);
    expect(text).toMatch(/Always a PR/);
    expect(text).toMatch(/Subject review\. Fix n ship/);
    expect(text).toMatch(/Groover ≠ Repertoire|Groover is not Repertoire/);
    expect(text).toMatch(/Loop until `\.xray\/state\/STATION\.md` is done/);
    expect(text).toMatch(/Do not use pacer timeouts as the work clock/);
    expect(text).toMatch(/Clean ticks \(every cycle\)/);
    expect(text).toMatch(/Name-dedupe is not a rewrite/);
    expect(text).toMatch(/Do not act on the stale prompt/);
    expect(text).toMatch(/Idle stop/);
    expect(text).toMatch(/WAVEBOARD are not active|WAVEBOARD are idle/);
    expect(text).toMatch(/Board clock \(honest design\)/);
    expect(text).toMatch(/Two idle pacers/);
    expect(text).toMatch(/subscribe_github_pr/);
    expect(text).toMatch(/Dispatch \(not a script\)/);
    expect(text).toMatch(/Cold brief/);
    expect(text).toMatch(/latest commit SHA on the branch under review/);
    expect(text).toMatch(/Station card \(`\.xray\/state\/STATION\.md`: intent, plan, git\)/);
    expect(text).toMatch(/send the new SHA before they verdict/);
    expect(text).toMatch(/When knowledge grows/);
    expect(text).toMatch(/### Cascade/);
    expect(text).toMatch(/Chat is not the brain/);
    expect(text).toMatch(/A reflection is not this capture/);
    expect(text).toMatch(/Wear, then review/);
    expect(text).toMatch(/Metamorphosis \(how an LLM becomes OP-PROC\)/);
    expect(text).toMatch(/opProcNames/);
    expect(text).toMatch(/Dest names are OP-PROC when worn/i);
    expect(text).toMatch(/in-context seats/);
    expect(text).toMatch(/Decision matrix to ship \(lead-owned\)/);
    expect(text).toMatch(/A — PR \+ CI/);
    expect(text).toMatch(/release:docs-check/);
    expect(text).toMatch(/Patch stamps/);
    expect(text).toMatch(/reconcile-version\.mjs --check/);
    expect(text).toMatch(/foundry release/);
    expect(text).toMatch(/Green CI is not publish/);
    expect(text).not.toMatch(/npm, Railway, spend, credentials — Ask-first/);
    expect(readFileSync(catalog, 'utf8')).toMatch(/LEAD-CADENCE\.md/);
    const overlay = JSON.parse(
      readFileSync(path.join(root, 'vendor/@0xray/repertoire/data/stack-overlay.json'), 'utf8'),
    ) as { signals: Array<{ name: string; definition: string }> };
    const planes = overlay.signals.find((signal) => signal.name === 'operating-planes');
    expect(planes?.definition).toMatch(/test\/ship/);
    expect(planes?.definition).toMatch(/the hero/);
    expect(planes?.definition).toMatch(/the catastrophe/);
    expect(planes?.definition).toMatch(/refreshes a changed definition/);
    expect(planes?.definition).toMatch(/not fully proved/);
    expect(planes?.definition).toMatch(/stamper strips that patch ref from shipped guides and shipped OP-PROC/);
    expect(planes?.definition).toMatch(/does not edit Station, NOTES, dest, or node_modules/);
    expect(overlay.signals.some((signal) => signal.name === 'six-planes')).toBe(false);
    const cascade = overlay.signals.find((signal) => signal.name === 'wake-cascade');
    expect(cascade?.definition).toMatch(/stamper strips that patch ref from shipped guides and shipped OP-PROC/);
    expect(cascade?.definition).toMatch(/Chat is not the brain/);
    expect(cascade?.definition).toMatch(/test then ship is the hero/);
    expect(cascade?.definition).toMatch(/the lead keeps control/);
    expect(cascade?.definition).toMatch(/A reflection is not this capture/);
    expect(text).toMatch(/Capture priority/);
    expect(text).toMatch(/heat-is-not-conviction/);
    expect(text).toMatch(/inference-cycle-invariant/);
    expect(text).toMatch(/governance-vote-invariant/);
    expect(text).toMatch(/thin-dispatch-invariant/);
    const byName = new Map(overlay.signals.map((signal) => [signal.name, signal.definition]));
    expect(byName.get('heat-is-not-conviction')).toMatch(/do not raise conviction/);
    expect(byName.get('heat-is-not-conviction')).toMatch(/does not append a confidence sample/);
    expect(byName.get('heat-is-not-conviction')).toMatch(/only when the diary contains that signal's name/);
    expect(byName.get('heat-is-not-conviction')).toMatch(/two definition words are not a hit/);
    expect(byName.get('heat-is-not-conviction')).toMatch(/a weak session score is not lifted to 0\.55/);
    expect(byName.get('heat-is-not-conviction')).toMatch(/a sample below 0\.55 is not recorded/);
    expect(byName.get('heat-is-not-conviction')).toMatch(/Constructing the organ does not append workspace samples/);
    expect(byName.get('heat-is-not-conviction')).toMatch(/refreshes a changed stack definition/);
    expect(text).toMatch(/does not append a confidence sample/);
    expect(text).toMatch(/only when the diary contains that signal's name/);
    expect(text).toMatch(/two definition words are not a hit/);
    expect(text).toMatch(/a weak session score is not lifted to 0\.55/);
    expect(text).toMatch(/a sample below 0\.55 is not recorded/);
    expect(text).toMatch(/Constructing the organ does not append workspace samples/);
    expect(byName.get('inference-cycle-invariant')).toMatch(/keyword map over session problem strings/);
    expect(byName.get('inference-cycle-invariant')).toMatch(/generateProposals also emits recurring-pattern titles/);
    expect(byName.get('inference-cycle-invariant')).toMatch(/inference-cycle-state\.json/);
    expect(byName.get('inference-cycle-invariant')).toMatch(/getInstance applies later options/);
    expect(byName.get('inference-cycle-invariant')).toMatch(/Governance failure rejects/);
    expect(byName.get('governance-vote-invariant')).toMatch(/clamped to 0\.\.1/);
    expect(byName.get('thin-dispatch-invariant')).toMatch(/at least 26 forces architect/);
  });

  it('rewires worn lead surfaces — no new skill file', () => {
    const millGate = path.join(root, 'grok-bot', 'skills', 'ship-ready-mill-gate', 'SKILL.md');
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Lead cadence \(syncopation\)/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Jargon is not the job/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Feat rebase/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Engine cadence/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Ship it local/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/### Planes/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/code, OP-PROC, model, suit, mill, host, and test\/ship/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Test then ship is the hero/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Ship without that proof is the catastrophe/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/stamper strips that patch ref from shipped guides and shipped OP-PROC/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/does not edit Station, NOTES, dest, or node_modules/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/It does not publish/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/not fully proved/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Do not freeze the live cut/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Chat is not the brain/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/A reflection is not this capture/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Capture priority/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/heat-is-not-conviction/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/does not append a confidence sample/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/only when the diary contains that signal's name/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/two definition words are not a hit/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/a weak session score is not lifted to 0\.55/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/a sample below 0\.55 is not recorded/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Constructing the organ does not append workspace samples/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/only when the diary contains that signal's name/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/two definition words are not a hit/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/a weak session score is not lifted to 0\.55/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/a sample below 0\.55 is not recorded/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Constructing the organ does not append workspace samples/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/The lead keeps control/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/wears the applicable 0xRay suit/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/latest commit SHA on the branch under review/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Station card/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Jargon is not the job/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Feat rebase/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Engine cadence/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Ship it local/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/### Planes/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/code, OP-PROC, model, suit, mill, host, and test\/ship/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Test then ship is the hero/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Ship without that proof is the catastrophe/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/stamper strips that patch ref from shipped guides and shipped OP-PROC/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/does not edit Station, NOTES, dest, or node_modules/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/It does not publish/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/not fully proved/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Do not freeze the live cut/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Chat is not the brain/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/A reflection is not this capture/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Capture priority/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/thin-dispatch-invariant/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/refreshes a changed stack definition/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/The lead keeps control/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/wears the applicable 0xRay suit/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/latest commit SHA on the branch under review/);
    expect(readFileSync(millGate, 'utf8')).toMatch(/Station card/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Clean ticks every cycle/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/WAVEBOARD are idle/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Subject review\. Fix n ship/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/Groover is not Repertoire/);
    expect(readFileSync(orchestrator, 'utf8')).toMatch(/opProcNames/);
    expect(readFileSync(agents, 'utf8')).toMatch(/LEAD-CADENCE\.md/);
    expect(existsSync(path.join(root, 'src', 'skills', 'lead-cadence', 'SKILL.md'))).toBe(false);
  });
});
