/**
 * Auto-generated test file for src/integrations/core/strray-integration.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { StringRayIntegration, createStringRayIntegration, strRayIntegration } from "./strray-integration";

describe("strray-integration", () => {
  describe("StringRayIntegration", () => {
    it("should instantiate", () => {
      const instance = new StringRayIntegration();
      expect(instance).toBeInstanceOf(StringRayIntegration);
    });
  });

  describe("createStringRayIntegration", () => {
    it("should be defined", () => {
      expect(createStringRayIntegration).toBeDefined();
    });
  });

  describe("strRayIntegration", () => {
    it("should be defined", () => {
      expect(strRayIntegration).toBeDefined();
    });
  });
});
